apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ellamma-ecommerce-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0a47cc4088d4ef69e
  directoryPerms: "700"
  basePath: "/roboshop"